name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: print py file
        run: echo "print py file"; cat test.py; 
        
      - name: run py file 
        run: echo "print py file"; python3 test.py; 
